version: '2'

services:

  angular-seed:
    build:
      context: .
      dockerfile: ./.docker/angular-seed.development.dockerfile
    command: npm start
    container_name: angular-seed-start
    image: angular-seed
    volumes:
      - .:/home/app/angular-seed
      - /home/app/angular-seed/node_modules
    networks:
      - dev-network
    ports:
      - '5555:5555'

  e2e-tests:
    build:
      context: .
      dockerfile: ./.docker/e2e-tests.dockerfile
      args:
        - http_proxy
        - https_proxy
    image: e2e-tests
    network_mode: "host"
    volumes:
        - .:/home/tester/gnss-site-manager
        - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
        - DISPLAY
        - http_proxy
        - https_proxy

networks:
  dev-network:
    driver: bridge
